### ISSUE TITLE
Add CADD for indels

### ISSUE THREAD

**Issue by jemten** [nf-core/raredisease#143]
The team behind CADD provide precomputed CADD scores for SNVs. The CADD scores for Indels needs to be calculated dynamically. Depending on how komplex the workflow becomes this might be splitted out into it's own subworkflow under SNV/INDEL annotation.

**Comment by maxulysse** [comment]
We're using the CADD plugin in VEP in the 2.7.1 sarek, haven't added that possibilities to the vep modules yet, since it's a bit messy: https://github.com/nf-core/sarek/blob/68b9930a74962f3c42eee71f51e6dd2646269199/main.nf#L3695
(actually it's the genesplicer one that is messy).
I'd love to see your ideas about that

**Comment by maxulysse** [comment]
Using the precomputed ones

**Comment by jemten** [comment]
done
